### ISSUE TITLE
Floor Count

### ISSUE THREAD

**Issue by ak0815** [appcelerator-modules/ti.coremotion#13]
Hello,

it is possible floorsAscended and implement floorsDescended?

greeting

**Comment by hansemannn** [comment]
Hi @ak0815, the properties will be available in the new ``Pedometer`` introduced in the 2.0.0 version of the module. You can follow the process in https://github.com/appcelerator-modules/ti.coremotion/pull/14. The current beta-version can be found [here](https://github.com/appcelerator-modules/ti.coremotion/releases/download/v2.0.0/ti.coremotion-iphone-2.0.0.zip).

**Comment by ak0815** [comment]
Hi @hansemannn
Thanks!
